/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiYtmusicSearchRouteImport } from './routes/api/ytmusic-search'
import { Route as ApiSpotifyToYtmusicRouteImport } from './routes/api/spotify-to-ytmusic'
import { Route as ApiQueueRouteImport } from './routes/api/queue'
import { Route as ApiMusicbrainzSearchRouteImport } from './routes/api/musicbrainz-search'
import { Route as ApiLiquidsoapRouteImport } from './routes/api/liquidsoap'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYtmusicSearchRoute = ApiYtmusicSearchRouteImport.update({
  id: '/api/ytmusic-search',
  path: '/api/ytmusic-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpotifyToYtmusicRoute = ApiSpotifyToYtmusicRouteImport.update({
  id: '/api/spotify-to-ytmusic',
  path: '/api/spotify-to-ytmusic',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQueueRoute = ApiQueueRouteImport.update({
  id: '/api/queue',
  path: '/api/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMusicbrainzSearchRoute = ApiMusicbrainzSearchRouteImport.update({
  id: '/api/musicbrainz-search',
  path: '/api/musicbrainz-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiquidsoapRoute = ApiLiquidsoapRouteImport.update({
  id: '/api/liquidsoap',
  path: '/api/liquidsoap',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/liquidsoap': typeof ApiLiquidsoapRoute
  '/api/musicbrainz-search': typeof ApiMusicbrainzSearchRoute
  '/api/queue': typeof ApiQueueRoute
  '/api/spotify-to-ytmusic': typeof ApiSpotifyToYtmusicRoute
  '/api/ytmusic-search': typeof ApiYtmusicSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/liquidsoap': typeof ApiLiquidsoapRoute
  '/api/musicbrainz-search': typeof ApiMusicbrainzSearchRoute
  '/api/queue': typeof ApiQueueRoute
  '/api/spotify-to-ytmusic': typeof ApiSpotifyToYtmusicRoute
  '/api/ytmusic-search': typeof ApiYtmusicSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/liquidsoap': typeof ApiLiquidsoapRoute
  '/api/musicbrainz-search': typeof ApiMusicbrainzSearchRoute
  '/api/queue': typeof ApiQueueRoute
  '/api/spotify-to-ytmusic': typeof ApiSpotifyToYtmusicRoute
  '/api/ytmusic-search': typeof ApiYtmusicSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/liquidsoap'
    | '/api/musicbrainz-search'
    | '/api/queue'
    | '/api/spotify-to-ytmusic'
    | '/api/ytmusic-search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/liquidsoap'
    | '/api/musicbrainz-search'
    | '/api/queue'
    | '/api/spotify-to-ytmusic'
    | '/api/ytmusic-search'
  id:
    | '__root__'
    | '/'
    | '/api/liquidsoap'
    | '/api/musicbrainz-search'
    | '/api/queue'
    | '/api/spotify-to-ytmusic'
    | '/api/ytmusic-search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiLiquidsoapRoute: typeof ApiLiquidsoapRoute
  ApiMusicbrainzSearchRoute: typeof ApiMusicbrainzSearchRoute
  ApiQueueRoute: typeof ApiQueueRoute
  ApiSpotifyToYtmusicRoute: typeof ApiSpotifyToYtmusicRoute
  ApiYtmusicSearchRoute: typeof ApiYtmusicSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ytmusic-search': {
      id: '/api/ytmusic-search'
      path: '/api/ytmusic-search'
      fullPath: '/api/ytmusic-search'
      preLoaderRoute: typeof ApiYtmusicSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spotify-to-ytmusic': {
      id: '/api/spotify-to-ytmusic'
      path: '/api/spotify-to-ytmusic'
      fullPath: '/api/spotify-to-ytmusic'
      preLoaderRoute: typeof ApiSpotifyToYtmusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/queue': {
      id: '/api/queue'
      path: '/api/queue'
      fullPath: '/api/queue'
      preLoaderRoute: typeof ApiQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/musicbrainz-search': {
      id: '/api/musicbrainz-search'
      path: '/api/musicbrainz-search'
      fullPath: '/api/musicbrainz-search'
      preLoaderRoute: typeof ApiMusicbrainzSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/liquidsoap': {
      id: '/api/liquidsoap'
      path: '/api/liquidsoap'
      fullPath: '/api/liquidsoap'
      preLoaderRoute: typeof ApiLiquidsoapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiLiquidsoapRoute: ApiLiquidsoapRoute,
  ApiMusicbrainzSearchRoute: ApiMusicbrainzSearchRoute,
  ApiQueueRoute: ApiQueueRoute,
  ApiSpotifyToYtmusicRoute: ApiSpotifyToYtmusicRoute,
  ApiYtmusicSearchRoute: ApiYtmusicSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
